### PR TITLE
Do not run pre_get_posts on our own query to set the transient #32

### LINKED ISSUE #32: v1.2.11 Can Cause Segmentation Fault in WP CLI / Infinite Loop on Front End of Website
Hey EDD team,

After upgrading to 1.2.11 I noticed that if I cleared all site transients `wp transient delete --all` and then attempted another WP CLI command I'd get a Segmentation Fault error. With some debugging I worked out it was because of the EDD Hide Download plugin.

Further investigation showed that an infinite loop is created because the `query_hidden_downloads()` method makes a `WP_Query` call. That in turn triggers the `pre_get_posts()` method that is hooked in, which then calls `get_hidden_download()` and `query_hidden_download()`. This process repeats until the Segmentation Fault occurs. 

The issue isn't limited to the WP CLI either. [If none of these conditions are met](https://github.com/awesomemotive/edd-hide-download/blob/a540e98078fd9eaa8bd846127f557906c384d7b2/edd-hide-download.php#L325-L350) you'll create an infinite loop on the front end of the website when the transient is `false`. It's only after you go to the admin area of the site and the transient data can be saved correctly (because of the aforementioned conditions) that everything starts working correctly.

### PR DESCRIPTION
**Pull request by cklosowski**
Fixes #32 

Changes requested:
1. Updates the `pre_get_posts` method to check if the query we are running is for the meta key `__edd_hide_download`, to avoid creating an infinite loop on itself.

To replicate this:
1. Visit the front end of your site and view a download list with the Downloads Block, or shortcode. Really anything that queries a list of downloads.
2. Go to your database and delete the transient `edd_hd_ids`, or use Debug Bar Console on the same page you are on and run `delete_transient( 'edd_hd_ids' );`
3. Refresh the page and watch the white screen/error happen.

### CODE REVIEW

**Comment by cklosowski** [comment]
Some things that need to be tested:
1. FES: Mark the product as hidden, and see if the vendor can still see the product on their dashboard.
2. EDD REST API: `/edd-api/products` should still show it when a user with the `edit_posts` capability is making the request with their token and key.
3. WP REST API: `/wp/v2/downloads` should still show the product when the user can `edit_posts`

**Comment by robincornett** [comment]
Tests:
- [x] When a download is hidden, the transient is generated.
- [x] Viewing the product grid, the hidden download is not visible.
- [x] As a vendor, I can still see the hidden product.
- [x] The download is visible in the WP REST API for an authenticated user.
- [x] The download is not visible in the WP REST API for an authenticated user.
- [x] The download is visible in the EDD Products API for an authenticated user.
- [x] The download is not visible in the EDD Products API for an unauthenticated user.
- [ ] The download is not visible in the EDD Products API for an unauthenticated user querying by product ID.

I happened to test this final one by accident--but due to how the EDD API works, the download meta isn't evaluated in the query for a single product.

**Comment by cklosowski** [comment]
@robincornett Is that a change in behavior from 1.2.11? I don't think it is.

**Comment by robincornett** [comment]
No, sorry, I meant to say that behavior is the same in this branch and master.

**Pull request merged**
